name: example
description: "A new Flutter project."
repository: https://github.com/tonyrbf96/flutter_packages
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.7
  rive_annotations:
    path: ../../rive_annotations

  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  rive_generator:
    path: ..

flutter:
  uses-material-design: true

  #
