name: rive_dart_importer
version: 0.13.7
description: Rive file importer for Dart
repository: https://github.com/tonyrbf96/flutter_packages
topics:
  - animation
  - ui
  - effects
  - widgets
  - widget
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  http: ">=0.13.3 <2.0.0"
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  mocktail:
  path: ^1.8.3
