name: rive_annotations
description: "A new Flutter package project."
version: 0.0.1
topics:
  - rive
  - build-runner
  - rive-generator
  - codegen
  - animation

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.12.0

dev_dependencies:
  flutter_lints: ^4.0.0

  #
