name: rive_generator
description: "A new Flutter package project."
version: 0.0.1
topics:
  - rive
  - rive-generator
  - build-runner
  - codegen
  - animation

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ">=5.2.0 <7.0.0"
  async: ^2.8.0
  build: ^2.4.1
  build_config: ^1.1.1
  collection: ^1.14.0
  meta: ^1.7.0
  path: ^1.8.0
  rive: ^0.13.7
  rive_annotations: ^0.0.1
  source_gen: ^1.5.0
  source_helper: ^1.3.4

dev_dependencies:
  build_runner: ^2.4.11
  build_test: ^2.1.7
  dart_style: 2.3.6
  test: ^1.20.0
  flutter_lints: ^3.0.0

flutter:
